import turtle as t

circleSize = 50
bodyWidth = 200
bodysuit = 200

t.up()
t.goto(0, 50)
t.down()
t.fillcolor("black")
t.begin_fill()
t.forward(bodyWidth)
t.left(90)
t.forward(bodysuit)
t.left(90)
t.forward(bodyWidth * 2)
t.left(90)
t.forward(bodysuit)
t.left(90)
t.forward(bodyWidth * 2)
t.end_fill()
t.up()
t.goto(-bodyWidth + circleSize * 2, 0)
t.down()
t.shape("turtle")
t.fillcolor("red")
t.begin_fill()
t.circle(circleSize)
t.end_fill()
t.up()
t.goto(bodyWidth - circleSize * 2, 0)
t.down()
t.fillcolor("red")
t.begin_fill()
t.circle(circleSize)
t.end_fill()
t.up()
t.goto(bodysuit, circleSize)
t.down()
t.done()
